// Generated by CoffeeScript 2.5.1
(function() {
  var pages, resetLocalStorage, resetSessionStorage;

  pages = ['Интересы', 'Учеба', 'Контакт', 'Фотоальбом', 'Тест', 'История'];

  resetLocalStorage = function() {
    var i, len, page;
    localStorage.clear();
    for (i = 0, len = pages.length; i < len; i++) {
      page = pages[i];
      localStorage.setItem(page, '0');
    }
  };

  resetSessionStorage = function() {
    var i, len, page;
    sessionStorage.clear();
    for (i = 0, len = pages.length; i < len; i++) {
      page = pages[i];
      sessionStorage.setItem(page, '0');
    }
  };

  $(function() {
    if (isNaN(localStorage.getItem(window.document.title)) || localStorage.getItem(window.document.title) === null) {
      resetLocalStorage();
    }
    if (isNaN(sessionStorage.getItem(window.document.title)) || sessionStorage.getItem(window.document.title) === null) {
      resetSessionStorage();
    }
    localStorage.setItem(window.document.title, (parseInt(localStorage.getItem(window.document.title)) + 1).toString());
    sessionStorage.setItem(window.document.title, (parseInt(sessionStorage.getItem(window.document.title)) + 1).toString());
  });

}).call(this);
