// Generated by CoffeeScript 2.5.1
(function() {
  var pages;

  pages = ['Интересы', 'Учеба', 'Контакт', 'Фотоальбом', 'Тест', 'История'];

  $(function() {
    $('#history-local').html(function() {
      var i, len, page, str;
      str = '';
      for (i = 0, len = pages.length; i < len; i++) {
        page = pages[i];
        str += '<tr><td>' + page + '</td><td>' + localStorage.getItem(page) + '</td></tr>';
      }
      return str;
    });
  });

  $(function() {
    $('#history-cookies').html(function() {
      var i, len, page, str;
      str = '';
      for (i = 0, len = pages.length; i < len; i++) {
        page = pages[i];
        str += '<tr><td>' + page + '</td><td>' + sessionStorage.getItem(page) + '</td></tr>';
      }
      return str;
    });
  });

}).call(this);
