// Generated by CoffeeScript 2.5.1
(function() {
  var btn, modal, span;

  modal = $('#myModal');

  btn = $('#myBtn');

  span = $('.close-modal');

  btn.click(function() {
    modal.css('display', 'block');
  });

  span.click(function() {
    modal.css('display', 'none');
  });

  $('window').click(function(event) {
    if (event.target === modal) {
      modal.css('display', 'none');
    }
  });

}).call(this);
