// Generated by CoffeeScript 2.5.1
(function() {
  var gallery_elements, i;

  gallery_elements = [];

  i = 1;

  while (i <= 9) {
    gallery_elements.push('images/' + i + '.jpg');
    i++;
  }

  $(function() {
    var i;
    var container;
    container = document.getElementById('gallery');
    i = 1;
    gallery_elements.forEach(photo => {
      var a;
      a = document.createElement('a');
      a.setAttribute('href', photo);
      a.setAttribute('data-lightbox', 'myphotos');
      a.innerHTML = ' <img src=" ' + photo + ' "> ';
      container.appendChild(a);
    });
  });

}).call(this);
