// Generated by CoffeeScript 2.5.1
(function() {
  var checkTime;

  checkTime = function(i) {
    if (i < 10) {
      i = '0' + i;
    }
    return i;
  };

  $(function startTime() {
    var today;
    var dd, h, m, mm, s, t, today, yyyy;
    today = new Date();
    h = today.getHours();
    m = today.getMinutes();
    s = today.getSeconds();
    today = new Date();
    dd = String(today.getDate()).padStart(2, '0');
    mm = String(today.getMonth() + 1).padStart(2, '0');
    //January is 0!
    yyyy = today.getFullYear();
    // add a zero in front of numbers<10
    m = checkTime(m);
    s = checkTime(s);
    $('#time').html(h + ':' + m + ':' + s);
    $('#date').html(dd + '.' + mm + '.' + yyyy);
    t = setTimeout((function() {
      startTime();
    }), 500);
  });

}).call(this);
