(print (format NIL "Чтение файла")) 
(with-open-file (stream "F:/lisp/in23.txt" :direction :input)
	(let ((x (parse-integer(read-line stream)))
		(a1 (parse-integer(read-line stream))) 
		(b1 (parse-integer(read-line stream))) 
		(c1 (parse-integer(read-line stream))) 
		(a2 (parse-integer(read-line stream))) 
		(b2 (parse-integer(read-line stream))) 
		(c2 (parse-integer(read-line stream))))
	(defun f7(a b c x)(+ (* a (expt x 3)) (* b x) c)) 
	(defun y7 (x) (/ (f7 a1 b1 c1 x) (f7 a2 b2 c2 x)))
	(setq y (y7 x))))
(with-open-file (stream "F:/lisp/out7.txt" :direction :output :if-exists :supersede) 
(format stream "~$" y)(close stream)) 
