(print (format NIL "Чтение файла")) 
(with-open-file (stream "D:\\lisp\\in23.txt" :direction :input)
	(let ((a1 (parse-integer(read-line stream))) 
		(b1 (parse-integer(read-line stream))) 
		(c1 (parse-integer(read-line stream))) 
		(a2 (parse-integer(read-line stream))) 
		(b2 (parse-integer(read-line stream))) 
		(c2 (parse-integer(read-line stream)))
		(a3 (parse-integer(read-line stream))) 
		(b3 (parse-integer(read-line stream))) 
		(c3 (parse-integer(read-line stream))) 
		(a4 (parse-integer(read-line stream))) 
		(b4 (parse-integer(read-line stream))) 
		(c4 (parse-integer(read-line stream))))
	(defun f23(m n k) (cos (- (/ (* pi m) n) k)))
	(defun y23() (/ (+ (- 1 (f23 a1 b1 c1)) (* 2 (f23 a2 b2 c2))) (+ 9 (- (f23 a3 b3 c3) (* 4 (f23 a4 b4 c4))))))
	(setq y (y23))))
(with-open-file (stream "D:\\lisp\\out23.txt" :direction :output :if-exists :supersede) 
(format stream "~,7f" y))
