-- MySQL Script generated by MySQL Workbench
-- Tue Dec 24 13:52:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Bus_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bus_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bus_station` DEFAULT CHARACTER SET utf8 ;
USE `Bus_station` ;

-- -----------------------------------------------------
-- Table `Bus_station`.`carrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus_station`.`carrier` (
  `id_carrier` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `house_number` INT NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`id_carrier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bus_station`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus_station`.`bus` (
  `license_plate` INT NOT NULL,
  `id_carrier` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `amount_of_sits` INT NOT NULL,
  `mark` VARCHAR(45) NOT NULL,
  `registry_number` INT NOT NULL,
  PRIMARY KEY (`license_plate`),
  INDEX `carrier_idx` (`id_carrier` ASC) VISIBLE,
  CONSTRAINT `carrier`
    FOREIGN KEY (`id_carrier`)
    REFERENCES `Bus_station`.`carrier` (`id_carrier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bus_station`.`settlements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus_station`.`settlements` (
  `id_settlements` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_settlements`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bus_station`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus_station`.`trip` (
  `id_trip` INT NOT NULL AUTO_INCREMENT,
  `departure_time` VARCHAR(45) NOT NULL,
  `arrival_time` VARCHAR(45) NOT NULL,
  `distance` INT NOT NULL,
  `schedule` VARCHAR(45) NOT NULL,
  `departure_station` VARCHAR(45) NOT NULL,
  `id_settlements` INT NOT NULL,
  PRIMARY KEY (`id_trip`),
  INDEX `settlements_idx` (`id_settlements` ASC) VISIBLE,
  CONSTRAINT `settlements`
    FOREIGN KEY (`id_settlements`)
    REFERENCES `Bus_station`.`settlements` (`id_settlements`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bus_station`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus_station`.`staff` (
  `id_staff` INT NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `street` INT NOT NULL,
  `house_number` INT NOT NULL,
  `apartment` INT NOT NULL,
  `post` VARCHAR(45) NOT NULL,
  `phone` INT NOT NULL,
  `expirience` INT NOT NULL,
  PRIMARY KEY (`id_staff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bus_station`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus_station`.`ticket` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `date_of_sale` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  `departure_date` VARCHAR(45) NOT NULL,
  `id_staff` INT NOT NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `staff_idx` (`id_staff` ASC) VISIBLE,
  CONSTRAINT `staff`
    FOREIGN KEY (`id_staff`)
    REFERENCES `Bus_station`.`staff` (`id_staff`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bus_station`.`waybill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bus_station`.`waybill` (
  `id_sale` INT NOT NULL AUTO_INCREMENT,
  `id_carrier` INT NOT NULL,
  `license_plate` INT NOT NULL,
  `id_settlements` INT NOT NULL,
  `id_trip` INT NOT NULL,
  `id_ticket` INT NOT NULL,
  `id_staff` INT NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `carrier_idx` (`id_carrier` ASC) VISIBLE,
  INDEX `plate_idx` (`license_plate` ASC) VISIBLE,
  INDEX `settlements_idx` (`id_settlements` ASC) VISIBLE,
  INDEX `trip_idx` (`id_trip` ASC) VISIBLE,
  INDEX `ticket_idx` (`id_ticket` ASC) VISIBLE,
  INDEX `staff_idx` (`id_staff` ASC) VISIBLE,
  CONSTRAINT `carrier`
    FOREIGN KEY (`id_carrier`)
    REFERENCES `Bus_station`.`carrier` (`id_carrier`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `plate`
    FOREIGN KEY (`license_plate`)
    REFERENCES `Bus_station`.`bus` (`license_plate`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `settlements`
    FOREIGN KEY (`id_settlements`)
    REFERENCES `Bus_station`.`settlements` (`id_settlements`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trip`
    FOREIGN KEY (`id_trip`)
    REFERENCES `Bus_station`.`trip` (`id_trip`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ticket`
    FOREIGN KEY (`id_ticket`)
    REFERENCES `Bus_station`.`ticket` (`id_ticket`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `staff`
    FOREIGN KEY (`id_staff`)
    REFERENCES `Bus_station`.`staff` (`id_staff`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
